#!/usr/bin/python3


import sys

if len(sys.argv) == 2:
  key = sys.argv[1]
  message = input()
  message = message.upper()
  alphabets = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  onlyAlpha = ""
  for i in range(len(message)):
    if message[i].isalpha():
      onlyAlpha += message[i]
  cipherWord = ""
  for i in range(len(onlyAlpha)):
    index_val = alphabets.index(onlyAlpha[i]) + int(key)
    cipherWord += alphabets[index_val]
  print(cipherWord)
